In [1]:
from tensorflow.keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [5]:
train_images.shape # (60000, 28, 28)
len(train_labels) # 60000
train_labels # array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
test_images.shape # (10000, 28, 28)
len(test_labels) # 10000
test_labels # array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [9]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

network = Sequential()
network.add(Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(Dense(10, activation='softmax'))

In [10]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [11]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [12]:
from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [13]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 5s 8ms/step - loss: 0.4455 - accuracy: 0.8705
Epoch 2/5
469/469 [==============================] - 3s 7ms/step - loss: 0.1127 - accuracy: 0.9673
Epoch 3/5
469/469 [==============================] - 3s 7ms/step - loss: 0.0721 - accuracy: 0.9789
Epoch 4/5
469/469 [==============================] - 5s 11ms/step - loss: 0.0486 - accuracy: 0.9847
Epoch 5/5
469/469 [==============================] - 3s 7ms/step - loss: 0.0368 - accuracy: 0.9888


In [14]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

313/313 [==============================] - 2s 5ms/step - loss: 0.0664 - accuracy: 0.9799


In [15]:
print(test_acc) 0.9799000024795532

0.9799000024795532


In [1]:
from tensorflow.keras.datasets import mnist
import numpy as np

In [2]:
x = np.array([12, 3, 6, 14, 7])
print(x)
print(x.ndim)

# 결과 
# [12  3  6 14  7]
# 1

[12  3  6 14  7]
1


In [2]:
import tensorflow as tf

In [3]:
x = tf.constant([[
    [5, 78, 2, 34, 0],
    [6, 79, 3, 35, 1],
    [7, 80, 4, 36, 2]
    ]])
print(x)
print(x.ndim)

# 결과 

tf.Tensor(
[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]], shape=(1, 3, 5), dtype=int32)
3

tf.Tensor(
[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]], shape=(1, 3, 5), dtype=int32)
3


In [22]:
x = tf.constant([[
    [5, 78, 2, 34, 0],
    [6, 79, 3, 35, 1],
    [7, 80, 4, 36, 2]
    ],[
    [5, 78, 2, 34, 0],
    [6, 79, 3, 35, 1],
    [7, 80, 4, 36, 2]]])

print(x)
print(x.ndim)
print(x.shape)

# 결과

# tf.Tensor(
# [[[ 5 78  2 34  0]
#   [ 6 79  3 35  1]
#   [ 7 80  4 36  2]]

#  [[ 5 78  2 34  0]
#   [ 6 79  3 35  1]
#   [ 7 80  4 36  2]]], shape=(2, 3, 5), dtype=int32)
# 3
# (2, 3, 5)

tf.Tensor(
[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]], shape=(2, 3, 5), dtype=int32)
3
(2, 3, 5)


In [19]:
x = np.array([[
    [5, 78, 2, 34, 0],
    [6, 79, 3, 35, 1],
    [7, 80, 4, 36, 2]
    ],[
    [5, 78, 2, 34, 0],
    [6, 79, 3, 35, 1],
    [7, 80, 4, 36, 2]]])
print(x)
print(x.ndim)
print(x.shape)

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]
3
(2, 3, 5)


In [12]:
x.shape

(3, 5)

In [24]:
from tensorflow.keras import models, layers

model = models.Sequential()
model.add(layers.Dense(32, input_shape=(784,))) 
## 32개의 유닛으로 된 밀집 층
model.add(layers.Dense(10))

In [26]:
model = models.Sequential()
model.add(layers.Dense(32, activation='relu', input_shape=(784,)))
model.add(layers.Dense(10, activation='softmax'))

In [27]:
input_tensor = layers.Input(shape=(784,))
x = layers.Dense(32, activation='relu')(input_tensor)
output_tensor = layers.Dense(10, activation='softmax')(x)

model = models.Model(inputs=input_tensor, outputs=output_tensor)